import { AdminUser, Product, Customer, Contract, DocItem, SupportTierInfo, Language, ProductBinary, License, HostActivation } from './types';

export const translations: Record<Language, Record<string, string>> = {
  EN: {
    dashboard: 'Dashboard',
    reports: 'Reports',
    audience: 'Audience',
    settings: 'Settings',
    overview: 'Project Overview',
    trackingPeriod: 'Tracking Period',
    exportPdf: 'Export PDF',
    exportCsv: 'Export CSV',
    customRange: 'Custom Range',
    searchReports: 'Search analytics...',
    totalUsers: 'Total Users',
    sessions: 'Sessions',
    bounceRate: 'Bounce Rate',
    avgDuration: 'Avg. Duration',
    usersOverTime: 'Users over time',
    currentPeriod: 'Current Period',
    previousPeriod: 'Previous Period',
    topPages: 'Top Pages',
    viewFullReport: 'View Full Report',
    language: 'Language',
    theme: 'Theme',
    analytics: 'Analytics',
    management: 'Enterprise Admin',
    home: 'Home',
    users: 'Users',
    products: 'Products',
    customers: 'Customers',
    billing: 'Audits',
    documentation: 'Documentation',
    support: 'Products',
    sitemap: 'Site Map',
    logOut: 'Log Out',
    welcomeBack: 'Welcome',
    activeProducts: 'Active Products',
    activeCustomers: 'Total Customers',
    projectedRevenue: 'Projected Contract Revenue',
    monthly: 'Monthly',
    annual: 'Annual',
    quickLinks: 'Quick Links',
    addNewUser: 'Add New User',
    addNewCustomer: 'Add New Customer',
    addNewProduct: 'Add Product',
    addNewContract: 'Create New Contract',
    adminUsers: 'Admin Users',
    customerUsers: 'Customer Users',
    searchUsers: 'Search users...',
    filterByCustomer: 'Filter by Customer',
    addBtn: 'Add',
    editBtn: 'Edit',
    deleteBtn: 'Delete',
    cancel: 'Cancel',
    save: 'Save',
    all: 'All',
    successSaved: 'Saved successfully!',
    successDeleted: 'Deleted successfully!',
    price: 'Price',
    sku: 'SKU',
    tier: 'Tier',
    family: 'Family',
    addProducts: 'Add Product',
    customerPortfolio: 'Customer Portfolio',
    activeInstances: 'Active Instances',
    purchasedInstances: 'Purchased Units',
    contracts: 'Licensing',
    term: 'Term',
    startDate: 'Start Date',
    endDate: 'End Date',
    financialTrend: 'Financial Cost Analysis',
    published: 'Published',
    unpublished: 'Draft',
    supportSla: 'Support SLAs',
    responseTime: 'Response Time',
    coverage: 'Coverage',
    channels: 'Channels'
  },
  FR: {
    dashboard: 'Tableau de bord',
    reports: 'Rapports',
    audience: 'Audience',
    settings: 'Paramètres',
    overview: 'Aperçu du projet',
    trackingPeriod: 'Période de suivi',
    exportPdf: 'Exporter PDF',
    exportCsv: 'Exporter CSV',
    customRange: 'Période personnalisée',
    searchReports: 'Rechercher des analyses...',
    totalUsers: 'Utilisateurs totaux',
    sessions: 'Sessions',
    bounceRate: 'Taux de rebond',
    avgDuration: 'Durée moyenne',
    usersOverTime: 'Utilisateurs au fil du temps',
    currentPeriod: 'Période actuelle',
    previousPeriod: 'Période précédente',
    topPages: 'Pages les plus visitées',
    viewFullReport: 'Afficher le rapport complet',
    language: 'Langue',
    theme: 'Thème',
    analytics: 'Analyses',
    management: 'Administration B&J',
    home: 'Accueil',
    users: 'Utilisateurs',
    products: 'Produits',
    customers: 'Clients',
    billing: 'Audits',
    documentation: 'Documentation',
    support: 'Produits',
    sitemap: 'Plan du Site',
    logOut: 'Se déconnecter',
    welcomeBack: 'Bienvenue',
    activeProducts: 'Produits Actifs',
    activeCustomers: 'Total Clients',
    projectedRevenue: 'Revenu contractuel projeté',
    monthly: 'Mensuel',
    annual: 'Annuel',
    quickLinks: 'Liens rapides',
    addNewUser: 'Ajouter un utilisateur',
    addNewCustomer: 'Ajouter un client',
    addNewProduct: 'Ajouter un produit',
    addNewContract: 'Nouveau Contrat',
    adminUsers: 'Utilisateurs Admin',
    customerUsers: 'Utilisateurs Clients',
    searchUsers: 'Rechercher des utilisateurs...',
    filterByCustomer: 'Filtrer par Client',
    addBtn: 'Ajouter',
    editBtn: 'Modifier',
    deleteBtn: 'Supprimer',
    cancel: 'Annuler',
    save: 'Enregistrer',
    all: 'Tous',
    successSaved: 'Enregistré avec succès !',
    successDeleted: 'Supprimé avec succès !',
    price: 'Prix',
    sku: 'SKU',
    tier: 'Niveau',
    family: 'Famille',
    addProducts: 'Ajouter un produit',
    customerPortfolio: 'Portefeuille Clients',
    activeInstances: 'Instances Actives',
    purchasedInstances: 'Unités Achetées',
    contracts: 'Licences',
    term: 'Durée',
    startDate: 'Date de début',
    endDate: 'Date de fin',
    financialTrend: 'Analyse des coûts financiers',
    published: 'Publié',
    unpublished: 'Brouillon',
    supportSla: 'SLA de support',
    responseTime: 'Temps de réponse',
    coverage: 'Couverture',
    channels: 'Canaux'
  },
  ES: {
    dashboard: 'Panel de Control',
    reports: 'Informes',
    audience: 'Audiencia',
    settings: 'Configuración',
    overview: 'Resumen del proyecto',
    trackingPeriod: 'Período de seguimiento',
    exportPdf: 'Exportar PDF',
    exportCsv: 'Exportar CSV',
    customRange: 'Rango personalizado',
    searchReports: 'Buscar análisis...',
    totalUsers: 'Usuarios totales',
    sessions: 'Sesiones',
    bounceRate: 'Tasa de rebote',
    avgDuration: 'Duración promedio',
    usersOverTime: 'Usuarios a lo largo del tiempo',
    currentPeriod: 'Período actual',
    previousPeriod: 'Período anterior',
    topPages: 'Páginas principales',
    viewFullReport: 'Ver informe completo',
    language: 'Idioma',
    theme: 'Tema',
    analytics: 'Análisis',
    management: 'Administración B&J',
    home: 'Inicio',
    users: 'Usuarios',
    products: 'Productos',
    customers: 'Clientes',
    billing: 'Auditorías',
    documentation: 'Documentación',
    support: 'Productos',
    sitemap: 'Mapa del Sitio',
    logOut: 'Cerrar Sesión',
    welcomeBack: 'Bienvenido',
    activeProducts: 'Productos Activos',
    activeCustomers: 'Total Clientes',
    projectedRevenue: 'Ingresos proyectados de contratos',
    monthly: 'Mensual',
    annual: 'Anuel',
    quickLinks: 'Enlaces Rápidos',
    addNewUser: 'Agregar Usuario',
    addNewCustomer: 'Agregar Cliente',
    addNewProduct: 'Agregar Producto',
    addNewContract: 'Crear Contrato',
    adminUsers: 'Usuarios Admin',
    customerUsers: 'Usuarios Clientes',
    searchUsers: 'Buscar usuarios...',
    filterByCustomer: 'Filtrar por Cliente',
    addBtn: 'Agregar',
    editBtn: 'Editar',
    deleteBtn: 'Eliminar',
    cancel: 'Cancelar',
    save: 'Guardar',
    all: 'Todos',
    successSaved: '¡Guardado con éxito!',
    successDeleted: '¡Eliminado con éxito!',
    price: 'Precio',
    sku: 'SKU',
    tier: 'Nivel',
    family: 'Familia',
    addProducts: 'Agregar Producto',
    customerPortfolio: 'Portafolio de Clientes',
    activeInstances: 'Instancias Actives',
    purchasedInstances: 'Unidades Adquiridas',
    contracts: 'Licencias',
    term: 'Plazo',
    startDate: 'Fecha Inicio',
    endDate: 'Fecha Fin',
    financialTrend: 'Análisis de Costos Financieros',
    published: 'Publicado',
    unpublished: 'Borrador',
    supportSla: 'SLA de Soporte',
    responseTime: 'Tiempo de respuesta',
    coverage: 'Cobertura',
    channels: 'Canales'
  }
};

export const initialUsers: AdminUser[] = [
  {
    uuid: 'u-101',
    firstName: 'Sarah',
    lastName: 'Connor',
    title: 'Senior DevOps Architect',
    phone: '+1 (555) 019-2831',
    email: 'sarah.connor@cyberdyne.io',
    customerId: 'c-1',
    customerName: 'Cyberdyne Systems',
    customerTierId: 'tier-gold',
    customerTier: 'Gold Support Model',
    notes: 'Primary Technical Contact for Cloud migrations',
    createDate: '2025-01-12',
    createdBy: 'System Provisioning',
    lastModified: '2026-05-18',
    lastModifiedBy: 'developerbe25@gmail.com',
    isAdminUser: true
  },
  {
    uuid: 'u-102',
    firstName: 'Bruce',
    lastName: 'Wayne',
    title: 'Enterprise Security Director',
    phone: '+1 (555) 332-9981',
    email: 'bwayne@waynecorp.com',
    customerId: 'c-2',
    customerName: 'Wayne Enterprises',
    customerTierId: 'tier-gold',
    customerTier: 'Gold Support Model',
    notes: 'Handles high-level encryption keys and licensing verification',
    createDate: '2025-02-15',
    createdBy: 'System Provisioning',
    lastModified: '2026-06-01',
    lastModifiedBy: 'developerbe25@gmail.com',
    isAdminUser: true
  },
  {
    uuid: 'u-103',
    firstName: 'Peter',
    lastName: 'Parker',
    title: 'Frontend Developer',
    phone: '+1 (555) 441-2918',
    email: 'pparker@dailybugle.com',
    customerId: 'c-3',
    customerName: 'Daily Bugle Press',
    customerTierId: 'tier-standard',
    customerTier: 'Standard Support Model',
    notes: 'Developer seeking access to Documentation API key',
    createDate: '2025-03-20',
    createdBy: 'Sarah Connor',
    lastModified: '2026-04-12',
    lastModifiedBy: 'Sarah Connor',
    isAdminUser: false
  },
  {
    uuid: 'u-104',
    firstName: 'Tony',
    lastName: 'Stark',
    title: 'Chief Innovation Officer',
    phone: '+1 (555) 999-0000',
    email: 'tony@starkindustries.com',
    customerId: 'c-4',
    customerName: 'Stark Industries',
    customerTierId: 'tier-gold',
    customerTier: 'Gold Support Model',
    notes: 'Owner of the high-compute AI cluster product licenses',
    createDate: '2025-01-01',
    createdBy: 'System Provisioning',
    lastModified: '2026-06-20',
    lastModifiedBy: 'developerbe25@gmail.com',
    isAdminUser: true
  },
  {
    uuid: 'u-105',
    firstName: 'Clark',
    lastName: 'Kent',
    title: 'Lead Investigative Journalist',
    phone: '+1 (555) 827-1111',
    email: 'ckent@dailyplanet.com',
    customerId: 'c-5',
    customerName: 'Daily Planet Inc',
    customerTierId: 'tier-standard',
    customerTier: 'Standard Support Model',
    notes: 'SLA Bronze level user accessing core news storage system',
    createDate: '2025-04-05',
    createdBy: 'Sarah Connor',
    lastModified: '2025-04-05',
    lastModifiedBy: 'Sarah Connor',
    isAdminUser: false
  }
];

export const initialProducts: Product[] = [
  {
    id: 'prod-01',
    name: 'BJ Cloud-Compute Engine',
    description: 'High-performance virtual machines with autoscaling and secure isolation.',
    tierName: 'Enterprise Core',
    sku: 'BJ-COMPUTE-ENT-001',
    unitPrice: 120.00,
    family: 'Virtualization & Cloud',
    customerIds: ['c-1', 'c-2', 'c-4'],
    notes: 'Configured with specialized Ubuntu & Rocky Linux pre-built templates',
    createDate: '2024-11-10',
    createdBy: 'Product Manager',
    lastModified: '2026-01-15',
    lastModifiedBy: 'developerbe25@gmail.com'
  },
  {
    id: 'prod-02',
    name: 'BJ Object-Storage Vault',
    description: 'Highly available, AES-256 encrypted storage buckets with cold-tier support.',
    tierName: 'Global Storage',
    sku: 'BJ-STORAGE-VAL-002',
    unitPrice: 15.50,
    family: 'Database & Storage',
    customerIds: ['c-1', 'c-2', 'c-3', 'c-4', 'c-5'],
    notes: 'Default storage repository for B&J clients',
    createDate: '2024-11-15',
    createdBy: 'Product Manager',
    lastModified: '2025-12-10',
    lastModifiedBy: 'Sarah Connor'
  },
  {
    id: 'prod-03',
    name: 'BJ Real-Time Data Guard',
    description: 'Autonomous firewall and active intrusion blocking backed by ML telemetry.',
    tierName: 'Shield Plus',
    sku: 'BJ-SECURITY-DG-003',
    unitPrice: 280.00,
    family: 'Cybersecurity',
    customerIds: ['c-2', 'c-4'],
    notes: 'Requires active tenant-level registration to B&J auth server',
    createDate: '2025-01-20',
    createdBy: 'Security Team',
    lastModified: '2026-03-24',
    lastModifiedBy: 'developerbe25@gmail.com'
  },
  {
    id: 'prod-04',
    name: 'BJ Gemini AI API Proxy',
    description: 'Server-side API router integrating Gemini 1.5 & 2.0 with custom enterprise grounding.',
    tierName: 'AI Studio Plus',
    sku: 'BJ-AI-GEMINI-004',
    unitPrice: 450.00,
    family: 'Artificial Intelligence',
    customerIds: ['c-1', 'c-4'],
    notes: 'Gemini API key is securely retrieved from Cloud Run backend configs',
    createDate: '2025-03-05',
    createdBy: 'AI Studio Builder',
    lastModified: '2026-06-25',
    lastModifiedBy: 'developerbe25@gmail.com'
  }
];

export const initialCustomers: Customer[] = [
  {
    id: 'c-1',
    name: 'Cyberdyne Systems',
    address: '1000 S. Technology Way, Los Angeles, CA 90025',
    primaryContactName: 'John Connor',
    primaryContactPhone: '+1 (555) 019-9000',
    primaryContactEmail: 'jconnor@cyberdyne.io',
    billingContactName: 'Robert Brewster',
    billingContactPhone: '+1 (555) 019-9111',
    billingContactEmail: 'rbrewster@cyberdyne.io',
    supportTier: 'Gold Support Model',
    supportContactName: 'Dev Support Desk',
    supportContactPhone: '+1 (555) 019-9222',
    supportContactEmail: 'support@cyberdyne.io',
    notes: 'Requires 99.99% uptime. High usage of AI compute cores.',
    createDate: '2025-01-10',
    createdBy: 'Sales Admin',
    lastModified: '2026-05-10',
    lastModifiedBy: 'developerbe25@gmail.com'
  },
  {
    id: 'c-2',
    name: 'Wayne Enterprises',
    address: '1007 Gotham Boulevard, Gotham City, NJ 07001',
    primaryContactName: 'Lucius Fox',
    primaryContactPhone: '+1 (555) 300-4000',
    primaryContactEmail: 'lfox@waynecorp.com',
    billingContactName: 'Alfred Pennyworth',
    billingContactPhone: '+1 (555) 300-4100',
    billingContactEmail: 'alfred@waynecorp.com',
    supportTier: 'Gold Support Model',
    supportContactName: 'Alfred Pennyworth',
    supportContactPhone: '+1 (555) 300-4200',
    supportContactEmail: 'emergency@waynecorp.com',
    notes: 'Critical customer. Custom military-grade data vaults enabled.',
    createDate: '2025-01-15',
    createdBy: 'Sales Admin',
    lastModified: '2026-06-12',
    lastModifiedBy: 'developerbe25@gmail.com'
  },
  {
    id: 'c-3',
    name: 'Daily Bugle Press',
    address: '220 E. 42nd St, New York, NY 10017',
    primaryContactName: 'J. Jonah Jameson',
    primaryContactPhone: '+1 (555) 888-1000',
    primaryContactEmail: 'jjj@dailybugle.com',
    billingContactName: 'Betty Brant',
    billingContactPhone: '+1 (555) 888-1010',
    billingContactEmail: 'bbrant@dailybugle.com',
    supportTier: 'Standard Support Model',
    supportContactName: 'IT Operations Team',
    supportContactPhone: '+1 (555) 888-2000',
    supportContactEmail: 'it@dailybugle.com',
    notes: 'Active subscriber to storage vaults. Complains about pricing regularly.',
    createDate: '2025-02-28',
    createdBy: 'Sales Rep',
    lastModified: '2025-08-15',
    lastModifiedBy: 'Sarah Connor'
  },
  {
    id: 'c-4',
    name: 'Stark Industries',
    address: '10880 Wilshire Blvd, Los Angeles, CA 90024',
    primaryContactName: 'Pepper Potts',
    primaryContactPhone: '+1 (555) 777-1000',
    primaryContactEmail: 'pepper@starkindustries.com',
    billingContactName: 'Happy Hogan',
    billingContactPhone: '+1 (555) 777-1100',
    billingContactEmail: 'happy@starkindustries.com',
    supportTier: 'Gold Support Model',
    supportContactName: 'Friday Support System',
    supportContactPhone: '+1 (555) 777-1200',
    supportContactEmail: 'friday@starkindustries.com',
    notes: 'Unlimited licenses on BJ-COMPUTE-ENT-001 and BJ-AI-GEMINI-004',
    createDate: '2025-01-01',
    createdBy: 'CEO Liaison',
    lastModified: '2026-06-24',
    lastModifiedBy: 'developerbe25@gmail.com'
  },
  {
    id: 'c-5',
    name: 'Daily Planet Inc',
    address: '1000 Metropolis Plaza, Metropolis, IL 62960',
    primaryContactName: 'Perry White',
    primaryContactPhone: '+1 (555) 444-9000',
    primaryContactEmail: 'pwhite@dailyplanet.com',
    billingContactName: 'Lois Lane',
    billingContactPhone: '+1 (555) 444-9100',
    billingContactEmail: 'llane@dailyplanet.com',
    supportTier: 'Standard Support Model',
    supportContactName: 'Help Desk Daily',
    supportContactPhone: '+1 (555) 444-9200',
    supportContactEmail: 'helpdesk@dailyplanet.com',
    notes: 'Uses basic object-storage tier with slow-retrieve archive rules.',
    createDate: '2025-03-14',
    createdBy: 'Sales Rep',
    lastModified: '2025-03-14',
    lastModifiedBy: 'Sales Rep'
  }
];

export const initialContracts: Contract[] = [
  {
    id: 'con-01',
    name: 'Cyberdyne Primary Compute License',
    description: 'Full reservation of 200 high-compute enterprise active instances.',
    customerId: 'c-1',
    customerName: 'Cyberdyne Systems',
    productSku: 'BJ-COMPUTE-ENT-001',
    productName: 'BJ Cloud-Compute Engine',
    unitPrice: 120.00,
    purchasedUnits: 250,
    activeUnits: 198,
    termMonths: 24,
    startDate: '2025-01-15',
    endDate: '2027-01-15',
    createDate: '2025-01-15',
    createdBy: 'Sales Administrator',
    lastUpdated: '2026-01-20',
    lastUpdatedBy: 'developerbe25@gmail.com'
  },
  {
    id: 'con-02',
    name: 'Wayne Secure Storage Covenant',
    description: 'Strategic high-availability encrypted storage vault.',
    customerId: 'c-2',
    customerName: 'Wayne Enterprises',
    productSku: 'BJ-STORAGE-VAL-002',
    productName: 'BJ Object-Storage Vault',
    unitPrice: 15.50,
    purchasedUnits: 1500,
    activeUnits: 1342,
    termMonths: 36,
    startDate: '2025-02-01',
    endDate: '2028-02-01',
    createDate: '2025-02-01',
    createdBy: 'Sales Administrator',
    lastUpdated: '2025-02-01',
    lastUpdatedBy: 'Sales Administrator'
  },
  {
    id: 'con-03',
    name: 'Stark AI Studio Gemini Proxy Tier',
    description: 'High-volume proxy pipeline directly routing to Google Gemini API.',
    customerId: 'c-4',
    customerName: 'Stark Industries',
    productSku: 'BJ-AI-GEMINI-004',
    productName: 'BJ Gemini AI API Proxy',
    unitPrice: 450.00,
    purchasedUnits: 15,
    activeUnits: 14,
    termMonths: 12,
    startDate: '2025-03-01',
    endDate: '2026-03-01',
    createDate: '2025-03-01',
    createdBy: 'Liaison Director',
    lastUpdated: '2026-02-25',
    lastUpdatedBy: 'developerbe25@gmail.com'
  },
  {
    id: 'con-04',
    name: 'Daily Bugle Backup System',
    description: 'Secondary storage node for digital news archives.',
    customerId: 'c-3',
    customerName: 'Daily Bugle Press',
    productSku: 'BJ-STORAGE-VAL-002',
    productName: 'BJ Object-Storage Vault',
    unitPrice: 15.50,
    purchasedUnits: 300,
    activeUnits: 290,
    termMonths: 12,
    startDate: '2025-03-01',
    endDate: '2026-03-01',
    createDate: '2025-03-01',
    createdBy: 'Sales Associate',
    lastUpdated: '2025-03-01',
    lastUpdatedBy: 'Sales Associate'
  }
];

export const initialDocs: DocItem[] = [
  {
    id: 'doc-01',
    title: 'Deploying Virtualized Containers on BJ-COMPUTE',
    category: 'Product Documentation',
    associatedProducts: ['BJ-COMPUTE-ENT-001'],
    isPublished: true,
    notes: 'Essential onboarding handbook for customer technical personnel',
    uploadDate: '2025-02-14',
    lastModified: '2026-04-10',
    fileSize: '4.2 MB'
  },
  {
    id: 'doc-02',
    title: 'Storage Lifecycle Rules & Automated Tiering',
    category: 'Product Documentation',
    associatedProducts: ['BJ-STORAGE-VAL-002'],
    isPublished: true,
    notes: 'Describes how to trigger cold storage transition to save cost',
    uploadDate: '2025-02-20',
    lastModified: '2025-02-20',
    fileSize: '1.8 MB'
  },
  {
    id: 'doc-03',
    title: 'Configuring Firewalls with Real-Time Data Guard',
    category: 'Support Documentation',
    associatedProducts: ['BJ-SECURITY-DG-003'],
    isPublished: false,
    notes: 'Draft manual pending certification by Chief Security Officer',
    uploadDate: '2025-05-12',
    lastModified: '2026-06-01',
    fileSize: '3.1 MB'
  },
  {
    id: 'doc-04',
    title: 'Integrating Gemini Large Language Models via BJ Proxy SDK',
    category: 'Product Documentation',
    associatedProducts: ['BJ-AI-GEMINI-004'],
    isPublished: true,
    notes: 'Full developer code samples in TypeScript, Python, and Go',
    uploadDate: '2025-03-10',
    lastModified: '2026-06-25',
    fileSize: '5.6 MB'
  }
];

export const initialSupportTiers: SupportTierInfo[] = [
  {
    id: 'tier-gold',
    name: 'Gold Support Model',
    responseTime: '2-4 Hours (P1-P2)',
    coverageHours: '24/7/365 Continuous',
    channels: ['Direct VIP Hotline', 'Priority Support Portal', 'Slack Dedicated Channel'],
    notes: '24/7 support with shorter response time',
    maxTickets: 999,
    directPhoneAccess: true,
    dedicatedLiaison: true
  },
  {
    id: 'tier-standard',
    name: 'Standard Support Model',
    responseTime: '2-4 Hours (P1), 8 Hours (P2)',
    coverageHours: 'Business Hours Only (M-F 9AM-5PM)',
    channels: ['Priority Support Portal', 'Email Ticketing Queue'],
    notes: 'Business Hours Only support with standard response time',
    maxTickets: 25,
    directPhoneAccess: false,
    dedicatedLiaison: false
  }
];

export const initialBinaries: ProductBinary[] = [
  {
    id: 'bin-01',
    fileName: 'bj-compute-orchestrator-v2.4.1-x64.tar.gz',
    version: 'v2.4.1',
    productSku: 'BJ-COMPUTE-ENT-001',
    productName: 'BJ Compute Hypervisor',
    fileSize: '142.4 MB',
    uploadDate: '2025-04-12',
    md5Checksum: 'f1e29c38ea299ff48209931b26da93c2',
    targetCustomerIds: ['c-1', 'c-2'],
    notes: 'Production stable build with security fixes for container virtualization.'
  },
  {
    id: 'bin-02',
    fileName: 'bj-secure-agent-v1.0.8-msi.zip',
    version: 'v1.0.8',
    productSku: 'BJ-SECURITY-DG-003',
    productName: 'BJ Cybersecurity Data-Guard',
    fileSize: '32.1 MB',
    uploadDate: '2025-06-01',
    md5Checksum: '92cd711ba0996faef20a289bcfe0013f',
    targetCustomerIds: ['c-1', 'c-3'],
    notes: 'Agent installer for Windows Server and Active Directory endpoints.'
  }
];

export const initialLicenses: License[] = [
  {
    id: 'lic-1',
    companyId: 'c-1',
    companyName: 'Acme Corporation',
    authPerson: 'Wile E. Coyote',
    licenseKey: '3',
    sku: 'BJ-COMPUTE-ENT-001',
    renewalDate: '2026-09-12',
    isActive: true,
    email: 'wile@acme.com'
  },
  {
    id: 'lic-2',
    companyId: 'c-2',
    companyName: 'Wayne Enterprises',
    authPerson: 'Bruce Wayne',
    licenseKey: '5',
    sku: 'BJ-SECURITY-DG-003',
    renewalDate: '2027-01-15',
    isActive: true,
    email: 'bruce@waynecorp.com'
  },
  {
    id: 'lic-3',
    companyId: 'c-4',
    companyName: 'Stark Industries',
    authPerson: 'Pepper Potts',
    licenseKey: '12',
    sku: 'BJ-COMPUTE-ENT-001',
    renewalDate: '2026-08-30',
    isActive: true,
    email: 'pepper@starkindustries.com'
  },
  {
    id: 'lic-4',
    companyId: 'c-5',
    companyName: 'Daily Planet Inc',
    authPerson: 'Perry White',
    licenseKey: '1',
    sku: 'BJ-STORAGE-VAL-002',
    renewalDate: '2026-12-05',
    isActive: false,
    email: 'pwhite@dailyplanet.com'
  }
];

export const initialHostActivations: HostActivation[] = [
  {
    id: 'act-1',
    contractId: 'con-01',
    contractIsActive: true,
    productId: 'prod-01',
    productSku: 'BJ-COMPUTE-ENT-001',
    customerId: 'c-1',
    customerName: 'Cyberdyne Systems',
    productName: 'BJ Cloud-Compute Engine',
    customerHostId: 'sys-cyber-01-mac-00:25:90:ff:11:12',
    licenseKey: 'LIC-COMPUTE-CYBERDYNE-sys-cyber-01',
    licenseActive: true,
    licenseStartDate: '2025-01-15',
    licenseEndDate: '2027-01-15'
  },
  {
    id: 'act-2',
    contractId: 'con-02',
    contractIsActive: true,
    productId: 'prod-02',
    productSku: 'BJ-STORAGE-VAL-002',
    customerId: 'c-2',
    customerName: 'Wayne Enterprises',
    productName: 'BJ Object-Storage Vault',
    customerHostId: 'sys-wayne-gotham-mac-00:14:22:01:23:45',
    licenseKey: 'LIC-STORAGE-WAYNE-sys-wayne-gotham',
    licenseActive: true,
    licenseStartDate: '2025-02-01',
    licenseEndDate: '2028-02-01'
  },
  {
    id: 'act-3',
    contractId: 'con-03',
    contractIsActive: true,
    productId: 'prod-04',
    productSku: 'BJ-AI-GEMINI-004',
    customerId: 'c-4',
    customerName: 'Stark Industries',
    productName: 'BJ Gemini AI API Proxy',
    customerHostId: 'sys-stark-jarvis-mac-12:34:56:78:90:ab',
    licenseKey: 'LIC-GEMINI-STARK-sys-stark-jarvis',
    licenseActive: true,
    licenseStartDate: '2025-03-01',
    licenseEndDate: '2026-03-01'
  }
];
